name: gpt2_finetune_english2latex_chatbot
hyperparameters:
    global_batch_size: 2
    weight_decay: 0.0
    learning_rate: 5e-5
    adam_epsilon: 1e-8
    warmup_steps: 0
    epochs: 1
    device: 'cuda'
    gradient_accumulation_steps: 1
    dataset_name: 'english_to_latex'
    train_batch_size: 2
    eval_batch_size: 32
environment:
    image: "hugcyrill/workshops:chat_0.1"
records_per_epoch: 25 # 50 examples, 2 per batch: 50/2 is 25 records for an epoch
resources:
    slots_per_trial: 1
min_validation_period:
  batches: 2
min_checkpoint_period:
  batches: 50
searcher:
    name: single
    metric: eval_loss
    max_length:
        epochs: 3
    smaller_is_better: true
max_restarts: 0
entrypoint: model_def:GPT2Finetune