name: opt125m_finetune_distributed
workspace: <my_workspace>
project: <my_project>
description: "OPT125m"
hyperparameters:
    global_batch_size: 64
    weight_decay: 0.0
    learning_rate: 5e-5
    adam_epsilon: 1e-8
    warmup_steps: 0
    epochs: 10
    gradient_accumulation_steps: 1
    dataset_name: 'PDS2'
    dataset_config: 'wikitext-2-raw-v1'
    use_hface: false
bind_mounts:
  - container_path: /mnt/efs
    host_path: /mnt/efs
    propagation: rprivate
    read_only: false
environment:
    image: "mendeza/mistral-rag-env:0.0.1"
records_per_epoch: 64 # There are 4696 examples total in the PDS2 dataset, shortening to 147 records per epoch for experimentation
resources:
    slots_per_trial: 2
    resource_pool: compute-pool
min_validation_period:
  batches: 10
profiling:
  begin_on_batch: 0
  enabled: true
min_checkpoint_period:
  batches: 30
searcher:
    name: single
    metric: eval_loss
    max_length:
        epochs: 3
    smaller_is_better: true
max_restarts: 0
entrypoint: python3 -m determined.launch.torch_distributed --trial model_def:OPTFinetuneTrial
