name: mistral_finetune_data_science_chatbot
workspace: HPE Instructors
project: finetune
description: "DS Workshop"
hyperparameters:
    global_batch_size: 1
    weight_decay: 0.0
    learning_rate: 5e-5
    adam_epsilon: 1e-8
    warmup_steps: 0
    epochs: 10
    gradient_accumulation_steps: 1
    dataset_name: 'PDS2'
environment:
    image: "mendeza/mistral-rag-env:0.0.1"
records_per_epoch: 147 # There are 4696 examples total in the PDS2 dataset, shortening to 147 records per epoch for experimentation
scheduling_unit: 2
resources:
    slots_per_trial: 1
    resource_pool: compute-pool-a10
min_validation_period:
  batches: 16
profiling:
  begin_on_batch: 0
  enabled: true
min_checkpoint_period:
  batches: 16
searcher:
    name: single
    metric: loss
    max_length:
        batches: 16
    smaller_is_better: true
max_restarts: 0
entrypoint: python3 -m determined.launch.torch_distributed --trial model_def:MistralFinetune